"use client"
import { useCallback, useEffect, useState } from "react"
import { createSupabaseBrowserClient } from "@/lib/supabase"
import { getBusinessId } from "@/lib/business"
import { currentUserName } from "@/lib/current-user"

// ──────────────────────────────────────────────────────────────────────────────
// Finance → Reimbursement (LHIKE ERP "Finance - Reimbursement" manual). A request
// list with an approve/decline workflow; on approval the request is ALSO recorded as
// a Book Keeping transaction (see pushBookkeepingTxn in bookkeeping-store). Source of
// truth = Supabase `reimbursements`; `pesowise_reimbursement` localStorage is now just
// a same-session read cache.
// ──────────────────────────────────────────────────────────────────────────────

export type ReimbStatus = "pending" | "approved" | "declined"

export const REIMB_MOPS = ["COD", "Cash", "Gcash", "Bank Transfer", "Credit Card", "Maya"]

export interface ReimbHistory { action: string; by: string; date: string; note?: string }

export interface Reimbursement {
  id: string
  control_no: string        // e.g. "2024-4"
  date: string              // "YYYY-MM-DD HH:mm:ss"
  payee_supplier: string
  department: string
  name: string              // requesting person
  purpose: string
  particulars: string
  type_of_expense: string
  shared_expense: string    // "" | "Yes" | "No" (gated by the General "shared expense" toggle)
  retail_share: number
  business_dev_share: number
  quantity: number
  unit_price: number
  total_payment: number     // quantity × unit_price
  mode_of_payment: string
  receipt_name: string
  status: ReimbStatus
  remarks: string
  recorded_txn_id: string   // Book Keeping txn id created on approval
  added_by: string
  added_date: string        // ISO
  approved_by: string
  approved_date: string     // "YYYY-MM-DD HH:mm:ss" when approved
  history: ReimbHistory[]
}

export const REIMB_ADDED_BY = "Admin User" // fallback only — real records stamp currentUserName()
export const SHARED_EXPENSE_OPTIONS = ["Yes", "No"]

export interface NewReimbInput {
  payee_supplier: string; department: string; name: string; purpose: string; particulars: string
  type_of_expense: string; quantity: number; unit_price: number; mode_of_payment: string; receipt_name: string
  shared_expense?: string; retail_share?: number; business_dev_share?: number
  date?: string; control_no?: string   // pre-generated by the form so display == saved
}

// Compute the next Control No ("{year}-{seq}") for display in the request form.
export function peekNextControlNo(list: Reimbursement[]): string {
  const year = new Date().getFullYear()
  return `${year}-${list.filter(r => String(r?.control_no || "").startsWith(`${year}-`)).length + 1}`
}
export function nowStampPublic(): string { return nowStamp() }

const KEY = "pesowise_reimbursement"

function nowStamp(): string {
  const d = new Date(); const p = (n: number) => String(n).padStart(2, "0")
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())} ${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())}`
}

function rowToReimb(r: any): Reimbursement {
  return {
    id: r.id, control_no: r.control_no || "", date: r.date || "",
    payee_supplier: r.payee_supplier || "", department: r.department || "", name: r.name || "",
    purpose: r.purpose || "", particulars: r.particulars || "", type_of_expense: r.type_of_expense || "",
    shared_expense: r.shared_expense || "", retail_share: Number(r.retail_share) || 0, business_dev_share: Number(r.business_dev_share) || 0,
    quantity: Number(r.quantity) || 0, unit_price: Number(r.unit_price) || 0, total_payment: Number(r.total_payment) || 0,
    mode_of_payment: r.mode_of_payment || "", receipt_name: r.receipt_name || "",
    status: r.status === "approved" || r.status === "declined" ? r.status : "pending",
    remarks: r.remarks || "", recorded_txn_id: r.recorded_txn_id || "",
    added_by: r.added_by || REIMB_ADDED_BY, added_date: r.added_date || r.created_at || new Date().toISOString(),
    approved_by: r.approved_by || "", approved_date: r.approved_date || "",
    history: Array.isArray(r.history) ? r.history : [],
  }
}

function readCache(): Reimbursement[] {
  try { const raw = localStorage.getItem(KEY); return raw ? JSON.parse(raw) : [] } catch { return [] }
}
function writeCache(list: Reimbursement[]) { try { localStorage.setItem(KEY, JSON.stringify(list)) } catch {} }

export function useReimbursements() {
  const [items, setItems] = useState<Reimbursement[]>(() => readCache())
  const [loading, setLoading] = useState(true)

  const refresh = useCallback(async () => {
    const businessId = await getBusinessId()
    if (!businessId) { setLoading(false); return }
    const supabase = createSupabaseBrowserClient()
    const { data, error } = await supabase.from("reimbursements").select("*").eq("business_id", businessId).order("created_at", { ascending: false })
    if (!error && data) { const list = data.map(rowToReimb); writeCache(list); setItems(list) }
    setLoading(false)
  }, [])

  useEffect(() => { refresh() }, [refresh])

  // Control No. = "{year}-{sequence}" (sequence increments per calendar year), computed
  // against the currently-loaded list — same as before, just Supabase-sourced now.
  const nextControlNo = useCallback((list: Reimbursement[]) => {
    const year = new Date().getFullYear()
    const seq = list.filter(r => r.control_no.startsWith(`${year}-`)).length + 1
    return `${year}-${seq}`
  }, [])

  const addRequest = useCallback(async (input: NewReimbInput) => {
    const businessId = await getBusinessId()
    if (!businessId) return
    const supabase = createSupabaseBrowserClient()
    const by = currentUserName() || REIMB_ADDED_BY
    const now = new Date().toISOString()
    const row = {
      business_id: businessId,
      control_no: input.control_no || nextControlNo(items), date: input.date || nowStamp(),
      payee_supplier: input.payee_supplier, department: input.department, name: input.name, purpose: input.purpose,
      particulars: input.particulars, type_of_expense: input.type_of_expense,
      shared_expense: input.shared_expense || "", retail_share: Number(input.retail_share) || 0, business_dev_share: Number(input.business_dev_share) || 0,
      quantity: Number(input.quantity) || 0, unit_price: Number(input.unit_price) || 0,
      total_payment: (Number(input.quantity) || 0) * (Number(input.unit_price) || 0),
      mode_of_payment: input.mode_of_payment, receipt_name: input.receipt_name,
      status: "pending", remarks: "", recorded_txn_id: null,
      added_by: by, added_date: now, approved_by: "", approved_date: "",
      history: [{ action: "Requested", by, date: now }],
    }
    const { error } = await supabase.from("reimbursements").insert(row)
    if (error) throw error
    await refresh()
  }, [items, nextControlNo, refresh])

  // Approve — caller supplies the Book Keeping txn id it created (so the link is recorded).
  const approve = useCallback(async (id: string, remarks: string, recordedTxnId: string) => {
    const current = items.find(r => r.id === id)
    if (!current) return
    const supabase = createSupabaseBrowserClient()
    const by = currentUserName() || REIMB_ADDED_BY
    const now = new Date().toISOString()
    const history = [...current.history, { action: "Approved & recorded to Book Keeping", by, date: now, note: remarks }]
    const { error } = await supabase.from("reimbursements").update({
      status: "approved", remarks, recorded_txn_id: recordedTxnId, approved_by: by, approved_date: nowStamp(), history,
    }).eq("id", id)
    if (error) throw error
    await refresh()
  }, [items, refresh])

  const decline = useCallback(async (id: string, remarks: string) => {
    const current = items.find(r => r.id === id)
    if (!current) return
    const supabase = createSupabaseBrowserClient()
    const by = currentUserName() || REIMB_ADDED_BY
    const now = new Date().toISOString()
    const history = [...current.history, { action: "Declined", by, date: now, note: remarks }]
    const { error } = await supabase.from("reimbursements").update({ status: "declined", remarks, history }).eq("id", id)
    if (error) throw error
    await refresh()
  }, [items, refresh])

  return { items, loaded: !loading, addRequest, approve, decline }
}
